"""
Render MonthlyReportData to a CFO-presentable PDF.

Engine: fpdf2 (pure Python - decision D1 amended; WeasyPrint needs Pango
native libraries that are unavailable on Windows dev and add weight on
Railway). Core Helvetica fonts only, so the output must stay latin-1 safe -
no em dashes, arrows, or sigma in literals here.
"""

from decimal import Decimal

from fpdf import FPDF

from api.services.report_builder import AnomalyLine, MonthlyReportData, SpendLine

# Brand palette (matches the web app's slate/indigo system)
_NAVY = (31, 58, 95)
_SLATE = (100, 116, 139)
_LIGHT_ROW = (243, 245, 248)
_HEADER_TEXT = (255, 255, 255)
_BODY_TEXT = (26, 26, 26)
_GREEN = (22, 130, 93)
_RED = (185, 50, 50)

_MARGIN = 14.0
_SEVERITY_COLORS = {"low": (180, 130, 0), "medium": (200, 90, 0), "high": _RED}


def _money(value: Decimal) -> str:
    return f"${value:,.2f}"


def _count(value: int) -> str:
    return f"{value:,}"


def _latin1(text: str) -> str:
    """
    Core Helvetica only supports latin-1; org names (Clerk) and tag labels
    (user-defined) can be any unicode. fpdf2 raises on unsupported chars,
    which would fail report generation outright - replace instead.
    """
    return text.encode("latin-1", errors="replace").decode("latin-1")


class _ReportPDF(FPDF):
    """A4 portrait with a branded footer on every page."""

    def footer(self) -> None:
        self.set_y(-12)
        self.set_font("helvetica", size=7)
        self.set_text_color(*_SLATE)
        self.cell(0, 5, "Generated by SpendOps AI", align="L")
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="R")


def _page_width(pdf: FPDF) -> float:
    return pdf.w - 2 * _MARGIN


def _header_band(pdf: _ReportPDF, data: MonthlyReportData) -> None:
    pdf.set_fill_color(*_NAVY)
    pdf.rect(0, 0, pdf.w, 34, style="F")
    pdf.set_xy(_MARGIN, 8)
    pdf.set_text_color(*_HEADER_TEXT)
    pdf.set_font("helvetica", style="B", size=16)
    pdf.cell(0, 8, "LLM Spend Report", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", size=10)
    period = f"{data.period_start:%B %Y}"
    if data.is_partial:
        period += f" (month to date through {data.period_end:%b %d})"
    pdf.cell(0, 6, _latin1(f"{data.org_name}  |  {period}"), new_x="LMARGIN", new_y="NEXT")
    pdf.set_y(42)


def _summary_cards(pdf: _ReportPDF, data: MonthlyReportData) -> None:
    cards: list[tuple[str, str, tuple[int, int, int] | None]] = [
        ("Total spend", _money(data.total_cost_usd), None),
        ("Requests", _count(data.total_requests), None),
        ("Tokens", _count(data.total_tokens), None),
    ]
    if data.mom_delta_pct is not None:
        color = _RED if data.mom_delta_pct > 0 else _GREEN
        # Partial periods compare against the SAME number of days last month
        # (see workers/reports._mom_comparison_range) - label accordingly.
        mom_label = "vs last month (MTD)" if data.is_partial else "vs last month"
        cards.append((mom_label, f"{data.mom_delta_pct:+.1f}%", color))
    if data.is_partial:
        cards.append(("Projected month end", _money(data.projected_month_cost_usd), None))

    card_w = _page_width(pdf) / len(cards)
    y = pdf.get_y()
    for i, (label, value, color) in enumerate(cards):
        x = _MARGIN + i * card_w
        pdf.set_xy(x, y)
        pdf.set_font("helvetica", size=8)
        pdf.set_text_color(*_SLATE)
        pdf.cell(card_w, 5, label.upper(), new_x="LEFT", new_y="NEXT")
        pdf.set_font("helvetica", style="B", size=13)
        pdf.set_text_color(*(color or _BODY_TEXT))
        pdf.cell(card_w, 7, value)
    pdf.set_y(y + 16)


def _section_title(pdf: _ReportPDF, title: str) -> None:
    if pdf.get_y() > pdf.h - 50:
        pdf.add_page()
    pdf.ln(3)
    pdf.set_font("helvetica", style="B", size=11)
    pdf.set_text_color(*_NAVY)
    pdf.cell(0, 7, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(*_NAVY)
    pdf.set_line_width(0.4)
    pdf.line(_MARGIN, pdf.get_y(), _MARGIN + _page_width(pdf), pdf.get_y())
    pdf.ln(2)


def _spend_table(pdf: _ReportPDF, lines: list[SpendLine], label_header: str) -> None:
    if not lines:
        pdf.set_font("helvetica", style="I", size=9)
        pdf.set_text_color(*_SLATE)
        pdf.cell(0, 6, "No data for this period.", new_x="LMARGIN", new_y="NEXT")
        return

    width = _page_width(pdf)
    cols = (width * 0.46, width * 0.22, width * 0.16, width * 0.16)

    pdf.set_font("helvetica", style="B", size=8)
    pdf.set_fill_color(*_NAVY)
    pdf.set_text_color(*_HEADER_TEXT)
    pdf.cell(cols[0], 6, f"  {label_header}", fill=True)
    pdf.cell(cols[1], 6, "Cost (USD)  ", fill=True, align="R")
    pdf.cell(cols[2], 6, "Requests  ", fill=True, align="R")
    pdf.cell(cols[3], 6, "% of total  ", fill=True, align="R", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("helvetica", size=9)
    pdf.set_text_color(*_BODY_TEXT)
    for i, line in enumerate(lines):
        if i % 2 == 1:
            pdf.set_fill_color(*_LIGHT_ROW)
        fill = i % 2 == 1
        pdf.cell(cols[0], 6, _latin1(f"  {line.label[:48]}"), fill=fill)
        pdf.cell(cols[1], 6, f"{_money(line.cost_usd)}  ", fill=fill, align="R")
        pdf.cell(cols[2], 6, f"{_count(line.requests)}  ", fill=fill, align="R")
        pdf.cell(
            cols[3], 6, f"{line.pct_of_total:.1f}%  ",
            fill=fill, align="R", new_x="LMARGIN", new_y="NEXT",
        )


def _anomaly_section(pdf: _ReportPDF, count: int, anomalies: list[AnomalyLine]) -> None:
    pdf.set_font("helvetica", size=9)
    pdf.set_text_color(*_BODY_TEXT)
    if count == 0:
        pdf.cell(0, 6, "No cost anomalies detected this period.", new_x="LMARGIN", new_y="NEXT")
        return

    plural = "anomaly" if count == 1 else "anomalies"
    headline = f"{count} cost {plural} detected. Largest spikes:"
    pdf.cell(0, 6, headline, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(1)
    for anomaly in anomalies:
        pdf.set_font("helvetica", style="B", size=9)
        pdf.set_text_color(*_SEVERITY_COLORS.get(anomaly.severity, _SLATE))
        pdf.cell(22, 6, anomaly.severity.upper())
        pdf.set_font("helvetica", size=9)
        pdf.set_text_color(*_BODY_TEXT)
        pdf.cell(
            0, 6,
            _latin1(
                f"{anomaly.detected_on}  {anomaly.scope_value[:40]}: "
                f"{_money(anomaly.baseline_usd)}/day baseline to {_money(anomaly.actual_usd)} "
                f"(+{anomaly.spike_pct}%)"
            ),
            new_x="LMARGIN", new_y="NEXT",
        )


def _savings_section(pdf: _ReportPDF, data: MonthlyReportData) -> None:
    pdf.set_font("helvetica", size=9)
    pdf.set_text_color(*_BODY_TEXT)
    if data.applied_recs_count == 0:
        pdf.cell(
            0, 6,
            "No savings recommendations were applied this period.",
            new_x="LMARGIN", new_y="NEXT",
        )
        return
    plural = "recommendation" if data.applied_recs_count == 1 else "recommendations"
    pdf.set_text_color(*_GREEN)
    pdf.set_font("helvetica", style="B", size=9)
    pdf.cell(
        0, 6,
        f"{data.applied_recs_count} savings {plural} applied, "
        f"projected {_money(data.applied_savings_usd)}/month saved.",
        new_x="LMARGIN", new_y="NEXT",
    )


def render_pdf(data: MonthlyReportData) -> bytes:
    pdf = _ReportPDF(orientation="P", unit="mm", format="A4")
    pdf.set_margins(_MARGIN, _MARGIN, _MARGIN)
    pdf.set_auto_page_break(auto=True, margin=18)
    pdf.add_page()

    _header_band(pdf, data)
    _summary_cards(pdf, data)

    _section_title(pdf, "Spend by provider")
    _spend_table(pdf, data.by_provider, "Provider")

    _section_title(pdf, "Top models")
    _spend_table(pdf, data.top_models, "Model")

    _section_title(pdf, "Spend by feature")
    _spend_table(pdf, data.by_feature, "Feature")

    _section_title(pdf, "Spend by team")
    _spend_table(pdf, data.by_team, "Team")

    _section_title(pdf, "Spend by customer")
    _spend_table(pdf, data.by_customer, "Customer")

    _section_title(pdf, "Anomalies")
    _anomaly_section(pdf, data.anomaly_count, data.top_anomalies)

    _section_title(pdf, "Realized savings")
    _savings_section(pdf, data)

    pdf.set_font("helvetica", style="I", size=7)
    pdf.set_text_color(*_SLATE)
    pdf.ln(4)
    pdf.multi_cell(
        0, 4,
        f"Generated on {data.generated_on:%Y-%m-%d}. OpenAI figures come from the provider "
        "Cost API. Anthropic figures are computed from list pricing and may drift slightly "
        "from your invoice.",
    )

    return bytes(pdf.output())
