-- =============================================================================
-- Migration: 20240101000000_initial_schema
-- Initial schema for SpendOps AI.
--
-- Conventions:
--   · UUIDs generated by gen_random_uuid() (Postgres 13+ built-in)
--   · All timestamps are UTC (TIMESTAMPTZ)
--   · created_at / updated_at on every mutable table
--   · RLS enabled on every org-scoped table
--   · Forward-only - rollback via a new migration
-- =============================================================================

-- ── Extensions ───────────────────────────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ── updated_at trigger ────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ─────────────────────────────────────────────────────────────────────────────
-- IDENTITY  (mirrors Clerk - synced via webhook)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE users (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email       TEXT UNIQUE NOT NULL,
    full_name   TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE organizations (
    id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name           TEXT NOT NULL,
    plan           TEXT NOT NULL DEFAULT 'trial',
    trial_ends_at  TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE organization_members (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role        TEXT NOT NULL DEFAULT 'admin',
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (org_id, user_id)
);

-- ─────────────────────────────────────────────────────────────────────────────
-- INTEGRATIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE integrations (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    provider      TEXT NOT NULL CHECK (provider IN ('openai', 'anthropic', 'gemini')),
    display_name  TEXT NOT NULL,
    api_key_enc   BYTEA NOT NULL,   -- AES-256-GCM; key lives in Supabase Vault
    status        TEXT NOT NULL DEFAULT 'active'
                  CHECK (status IN ('active', 'error', 'revoked')),
    last_synced_at  TIMESTAMPTZ,
    last_error      TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (org_id, provider, display_name)
);
CREATE INDEX idx_integrations_org_status ON integrations (org_id, status);
CREATE TRIGGER trg_integrations_updated_at
    BEFORE UPDATE ON integrations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- CORE ANALYTICS  (high write - ingestion workers land here)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE usage_events (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    integration_id  UUID REFERENCES integrations(id) ON DELETE SET NULL,
    provider        TEXT NOT NULL,
    model           TEXT NOT NULL,
    api_key_label   TEXT,
    -- denormalized after tag-rule evaluation
    feature_tag     TEXT,
    team_tag        TEXT,
    customer_tag    TEXT,
    env_tag         TEXT,
    input_tokens    BIGINT NOT NULL DEFAULT 0,
    output_tokens   BIGINT NOT NULL DEFAULT 0,
    cached_tokens   BIGINT NOT NULL DEFAULT 0,
    cost_usd        NUMERIC(14, 8) NOT NULL DEFAULT 0,
    request_count   INT NOT NULL DEFAULT 0,
    bucket_hour     TIMESTAMPTZ NOT NULL,  -- floored to UTC hour
    raw_meta        JSONB,
    ingested_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_usage_events_org_hour    ON usage_events (org_id, bucket_hour DESC);
CREATE INDEX idx_usage_events_org_feature ON usage_events (org_id, feature_tag, bucket_hour DESC);
CREATE INDEX idx_usage_events_org_model   ON usage_events (org_id, model, bucket_hour DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- READ-OPTIMIZED ROLLUP  (dashboard always hits this - never raw usage_events)
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE daily_cost_summaries (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    day             DATE NOT NULL,
    provider        TEXT NOT NULL,
    model           TEXT NOT NULL,
    feature_tag     TEXT NOT NULL DEFAULT '',
    team_tag        TEXT NOT NULL DEFAULT '',
    customer_tag    TEXT NOT NULL DEFAULT '',
    env_tag         TEXT NOT NULL DEFAULT '',
    total_cost_usd  NUMERIC(14, 6) NOT NULL DEFAULT 0,
    total_requests  BIGINT NOT NULL DEFAULT 0,
    total_tokens    BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (org_id, day, provider, model, feature_tag, team_tag, customer_tag, env_tag)
);
CREATE INDEX idx_daily_cost_summaries_org_day ON daily_cost_summaries (org_id, day DESC);
CREATE TRIGGER trg_daily_cost_summaries_updated_at
    BEFORE UPDATE ON daily_cost_summaries
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ─────────────────────────────────────────────────────────────────────────────
-- TAGGING
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE tags (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id      UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    type        TEXT NOT NULL CHECK (type IN ('feature', 'team', 'customer', 'env')),
    name        TEXT NOT NULL,
    color       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (org_id, type, name)
);

CREATE TABLE tag_rules (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    tag_id          UUID NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    match_type      TEXT NOT NULL CHECK (match_type IN ('regex', 'substring', 'exact')),
    match_pattern   TEXT NOT NULL,
    priority        INT NOT NULL DEFAULT 100,
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_tag_rules_org_enabled_priority ON tag_rules (org_id, enabled, priority);

-- ─────────────────────────────────────────────────────────────────────────────
-- INTELLIGENCE
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE budgets (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    scope_type      TEXT NOT NULL CHECK (scope_type IN ('global', 'tag', 'model')),
    scope_value     TEXT,
    monthly_limit   NUMERIC(12, 2) NOT NULL,
    alert_at_pct    INT NOT NULL DEFAULT 80,
    hard_cap        BOOLEAN NOT NULL DEFAULT FALSE,
    created_by      UUID REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_budgets_updated_at
    BEFORE UPDATE ON budgets
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE anomalies (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id       UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    detected_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    scope_kind   TEXT NOT NULL,
    scope_value  TEXT,
    baseline_usd NUMERIC(14, 6) NOT NULL,
    actual_usd   NUMERIC(14, 6) NOT NULL,
    spike_pct    INT NOT NULL,
    severity     TEXT NOT NULL CHECK (severity IN ('low', 'medium', 'high')),
    status       TEXT NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open', 'acked', 'dismissed')),
    context      JSONB,
    notified_at  TIMESTAMPTZ
);
CREATE INDEX idx_anomalies_org_detected ON anomalies (org_id, detected_at DESC);

CREATE TABLE recommendations (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id                UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    type                  TEXT NOT NULL
                          CHECK (type IN ('model_swap', 'caching', 'batch', 'other')),
    title                 TEXT NOT NULL,
    description           TEXT NOT NULL,
    projected_savings_usd NUMERIC(12, 2),
    confidence            NUMERIC(4, 2),
    evidence              JSONB,
    status                TEXT NOT NULL DEFAULT 'new'
                          CHECK (status IN ('new', 'applied', 'dismissed')),
    generated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    resolved_at           TIMESTAMPTZ
);
CREATE INDEX idx_recommendations_org_status ON recommendations (org_id, status, projected_savings_usd DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- THIRD-PARTY INTEGRATIONS
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE slack_integrations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id          UUID UNIQUE NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    workspace_id    TEXT NOT NULL,
    channel_id      TEXT NOT NULL,
    channel_name    TEXT NOT NULL,
    bot_token_enc   BYTEA NOT NULL,  -- AES-256-GCM
    installed_by    UUID REFERENCES users(id),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_slack_integrations_updated_at
    BEFORE UPDATE ON slack_integrations
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE billing (
    org_id                  UUID PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
    stripe_customer_id      TEXT,
    stripe_subscription_id  TEXT,
    plan                    TEXT NOT NULL DEFAULT 'trial',
    status                  TEXT NOT NULL DEFAULT 'active',
    current_period_end      TIMESTAMPTZ,
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE TRIGGER trg_billing_updated_at
    BEFORE UPDATE ON billing
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE reports (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    type          TEXT NOT NULL DEFAULT 'cfo_pdf',
    period_start  DATE NOT NULL,
    period_end    DATE NOT NULL,
    r2_object_key TEXT,
    generated_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_reports_org_period ON reports (org_id, period_start DESC);

CREATE TABLE audit_events (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id        UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
    actor_user_id UUID REFERENCES users(id),
    action        TEXT NOT NULL,
    target_kind   TEXT,
    target_id     UUID,
    metadata      JSONB,
    at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX idx_audit_events_org_at ON audit_events (org_id, at DESC);

-- ─────────────────────────────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- Template: org_id = (auth.jwt()->>'org_id')::uuid
-- Applied to every table that stores customer data.
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE organization_members    ENABLE ROW LEVEL SECURITY;
ALTER TABLE integrations            ENABLE ROW LEVEL SECURITY;
ALTER TABLE usage_events            ENABLE ROW LEVEL SECURITY;
ALTER TABLE daily_cost_summaries    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tags                    ENABLE ROW LEVEL SECURITY;
ALTER TABLE tag_rules               ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE anomalies               ENABLE ROW LEVEL SECURITY;
ALTER TABLE recommendations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE slack_integrations      ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_events            ENABLE ROW LEVEL SECURITY;

CREATE POLICY organization_members_iso  ON organization_members  USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY integrations_iso          ON integrations          USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY usage_events_iso          ON usage_events          USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY daily_cost_summaries_iso  ON daily_cost_summaries  USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY tags_iso                  ON tags                  USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY tag_rules_iso             ON tag_rules             USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY budgets_iso               ON budgets               USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY anomalies_iso             ON anomalies             USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY recommendations_iso       ON recommendations       USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY slack_integrations_iso    ON slack_integrations    USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY billing_iso               ON billing               USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY reports_iso               ON reports               USING (org_id = (auth.jwt()->>'org_id')::uuid);
CREATE POLICY audit_events_iso          ON audit_events          USING (org_id = (auth.jwt()->>'org_id')::uuid);
